### ISSUE TITLE
PNG images generated are cropped for some alleles

### ISSUE THREAD

**Issue by hchetia** [Illumina/GraphAlignmentViewer#16]
Hi
I am using this tool to view my EXPHunter results.
I observed that some png files for eg ATN1:CAG or DMPK were cropped while others HTT were fine. It seems that since these alleles were shorter in sequence, its consequent image was affected while for longer alleles it wasn't.
How can I resolve this?
![image](https://user-images.githubusercontent.com/64626735/127063884-ad9140cd-82ec-47b6-8989-1d67092fc6b1.png)
Also, is there any interactive viewing tool with similar functionality as GAV?

**Comment by egor-dolzhenko** [comment]
Hi @hchetia, perhaps you may be interested in trying [REViewer](https://github.com/Illumina/REViewer)? REViewer has a companion tool https://github.com/broadinstitute/reviewer2 designed to help with reviewing large collections of plots.

**Comment by hchetia** [comment]
Thank you for the suggestion.
